# Generated by Django 4.2.7 on 2023-11-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_utilizador_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizador',
            old_name='name',
            new_name='nome',
        ),
    ]
