# Generated by Django 4.2.7 on 2023-11-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_name_utilizador_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'managed': False},
        ),
    ]
