# Generated by Django 4.2.7 on 2023-11-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'managed': True},
        ),
    ]
