# Generated by Django 4.2.7 on 2023-12-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_utilizador_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('id_estado', models.IntegerField()),
            ],
            options={
                'db_table': 'componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('id_estado', models.IntegerField()),
            ],
            options={
                'db_table': 'fornecedor',
                'managed': False,
            },
        ),
    ]
