# Generated by Django 4.2.7 on 2023-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('tpdoc', models.CharField()),
                ('ndoc', models.IntegerField()),
                ('id_estado', models.IntegerField()),
                ('valortotal', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('tpdoc', models.CharField()),
                ('ndoc', models.IntegerField()),
                ('id_moeda', models.CharField()),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
    ]
