# Generated by Django 4.2.7 on 2023-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_compra_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_Componete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.IntegerField()),
                ('id_componente', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.CharField()),
            ],
            options={
                'db_table': 'compra_componente',
                'managed': False,
            },
        ),
    ]
