# Generated by Django 4.2.7 on 2023-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_compra_componete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_Componente',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('id_componente', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.CharField()),
            ],
            options={
                'db_table': 'compra_componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tipomaoobra',
            fields=[
                ('id_tipomaoobra', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('custo_hora', models.CharField()),
            ],
            options={
                'db_table': 'tipomaoobra',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Compra_Componete',
        ),
    ]
