# Generated by Django 4.2.7 on 2023-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_compra_componente_tipomaoobra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id_tipoequipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoequipamento',
                'managed': False,
            },
        ),
    ]
