# Generated by Django 4.1.13 on 2023-12-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_equipamentocompatrib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipamentoCompAtrib',
        ),
    ]
