from django.urls import path
from backend.views import(
    dashboard, 
    generic_list, 
    error404, 
    Sem_Acesso,
    delete_record, 
    edit_record, 
    edit_componente, 
    new_order, 
    save_encomenda, 
    new_prod,
    new_utilizador, 
    save_utilizador,     
    criar_mao_obra, 
    form_create_componente, 
    get_atributo_options, 
    create_componente, 
    create_equipamento, 
    new_prod_existente, 
    create_producao_equip_existente, 
    fn_populate_equipamento_comp_atrib,
    list_compra_FR_doc,
    receber_encomenda,
    import_componente_json,
    import_componente_html,
    edit_fornecedor,
    detalhes_fornecedor
)
from frontend.views import(
    index, 
    kanban,
    login_utilizador, 
    logout_utilizador, 
    equipamento_type, 
    detalhes_equipamento, 
    fulllogin,
    aplicarfiltros, 
    aplicarpreco,
    pesquisa_equipamento, 
    usercompras, 
    detalhes_venda,
)

urlpatterns = [
    path("dashboard/", dashboard),
    path("order/create/", new_order),
    path("componente/import/", import_componente_html),
    path("equipamento/create/", new_prod),
    path("producao/create/", new_prod_existente),
    path("utilizador/create/", new_utilizador),
    path("utilizador/save/", save_utilizador), 
    path('save_utilizador/', save_utilizador, name='save_utilizador'),       
    path("404/", error404),
    path("sem_acesso/", Sem_Acesso),    
    path("<str:table_name>/list/", generic_list, name='generic_list'),
    path("<str:table_name>/editar/<int:record_id>/", edit_record, name='edit_record'),
    path("", index),
    path('kanban/', kanban, name='kanban'),
    path('tipo/<int:tipo>', equipamento_type, name='equipamento_type'),
    path('delete_record/<str:table_name>/<int:record_id>/', delete_record, name='delete_record'),
    path('login/', login_utilizador, name='login'),
    path('logout/', logout_utilizador, name='logout'),
    path('componente/edit/<int:record_id>/', edit_componente, name='edit_componente'),
    path('fornecedor/edit/<int:record_id>/', edit_fornecedor, name='edit_fornecedor'),
    path('save_encomenda/', save_encomenda, name='save_encomenda'),
    path('criar_mao_obra/', criar_mao_obra, name='criar_mao_obra'),
    path('pesquisa_equipamento/', pesquisa_equipamento, name='pesquisa_equipamento'),
    path('equipamento/<int:equipamento_id>/', detalhes_equipamento, name='detalhes_equipamento'),
    path('mango/', fn_populate_equipamento_comp_atrib),
    path("componente/create", form_create_componente),
    path("get_atributo_options/", get_atributo_options, name='get_atributo_options'),
    path('create_componente/', create_componente, name='create_componente'),
    path('create_equipamento/', create_equipamento, name='create_equipamento'),
    path('create_producao_equip_existente/', create_producao_equip_existente, name='create_producao_equip_existente'),
    path('fulllogin/', fulllogin, name='login'),
    path("compra/list/fr", list_compra_FR_doc, name='list_compra_FR_doc'),
    path('receive_order/<int:record_id>/', receber_encomenda, name='receber_encomenda'),
    path("import_componente_json/", import_componente_json, name='import_componente_json'),
    path('aplicarfiltros/', aplicarfiltros, name='aplicarfiltros'),
    path('aplicarpreco/', aplicarpreco, name='aplicarpreco'),
    path('detalhes_venda/<int:venda_id>/', detalhes_venda, name='detalhes_venda'),
    path('detalhes_fornecedor/<int:fornecedor_id>/', detalhes_fornecedor, name='detalhes_fornecedor'),
    path('usercompras/', usercompras, name='usercompras'),   
    
]
